language: php

stage: "Tests not hitting api endpoints"

php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - alfred_workflow_data=./tests/mo.com.sleeplessmind.time
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --group=default --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover

jobs:
  include:
    - stage: "Tests hitting api endpoints — 72 lowest"
      php: 7.2
      script: vendor/bin/phpunit --group=timerServicesApiCalls --coverage-text --coverage-clover=coverage.clover
      env: COMPOSER_FLAGS="--prefer-lowest"
    - stage: "Tests hitting api endpoints — 73 lowest"
      php: 7.3
      script: vendor/bin/phpunit --group=timerServicesApiCalls --coverage-text --coverage-clover=coverage.clover
      env: COMPOSER_FLAGS="--prefer-lowest"
    - stage: "Tests hitting api endpoints — 74 lowest"
      php: 7.4
      script: vendor/bin/phpunit --group=timerServicesApiCalls --coverage-text --coverage-clover=coverage.clover
      env: COMPOSER_FLAGS="--prefer-lowest"
    - stage: "Tests hitting api endpoints — 72"
      php: 7.2
      script: vendor/bin/phpunit --group=timerServicesApiCalls --coverage-text --coverage-clover=coverage.clover
      env: COMPOSER_FLAGS=""
    - stage: "Tests hitting api endpoints — 73"
      php: 7.3
      script: vendor/bin/phpunit --group=timerServicesApiCalls --coverage-text --coverage-clover=coverage.clover
      env: COMPOSER_FLAGS=""
    - stage: "Tests hitting api endpoints — 74"
      php: 7.4
      script: vendor/bin/phpunit --group=timerServicesApiCalls --coverage-text --coverage-clover=coverage.clover
      env: COMPOSER_FLAGS=""
